name: Deployment (Container)
on:
  push:
    branches:
      - main

env:
  GOOS: linux
  GO_VERSION: "1.24.0"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Install dependencies
        run: go mod download
      - name: Verify dependencies
        run: go mod verify
      - name: Run linter
        uses: golangci/golangci-lint-action@v8
        with:
          version: v2.1
  # Job 2: Testing
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    # Run tests in parallel with linting
    steps:
      # Step 1: Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Go environment
      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: ${{ env.GO_VERSION }}

      # Step 3: Cache Go modules
      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      # Step 4: Download dependencies
      - name: Download dependencies
        run: go mod download

      # Step 5: Run tests with coverage
      - name: Run tests
        run: |
          go test -v -race -coverprofile=coverage.out -covermode=atomic ./...

  # Job 3: Build
  build:
    name: Build Application
    runs-on: ubuntu-latest
    # Build only after lint and test jobs pass
    needs: [lint, test]
    steps:
      # Step 1: Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Go environment
      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: ${{ env.GO_VERSION }}

      # Step 3: use local action to load dpes and cache them
      - name: Load & Cache deps
        id: cache-deps
        uses: ./.github/actions/cached-deps

      # Step 4: Output info
      - name: Output info
        run: echo "Cache used? ${{ steps.cache-deps.outputs.used-cache }}"

      # Step 5: Build the application
      - name: Build application
        run: |
          # Create build directory
          mkdir -p buil

          # Build with optimizations and version info
          CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build \
            -ldflags="-w -s -X main.version=${{ github.sha }} -X main.buildTime=$(date -u +%Y-%m-%dT%H:%M:%SZ)" \
            -o build/echo-api \
            .
  information:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run JS Custom action
        uses: ./.github/actions/build-go-echo
