name: Deployment (Container)
on:
  push:
    branches:
      - main

env:
  GOOS: linux

jobs:
  test:
    environment: testing
    runs-on: ubuntu-latest
    container:
      image: go:1.25.0
      env:
        GOOS: linux
    services:
      redis:
        image: redis
        env:
          THIS_ENV: example_env
        # ports:
        #   - 6379:6379
      # my-surrealdb:
      # image: surrealdb/surrealdb
    env:
      PORT: 1323
      REDIS_HOST: redis
      REDIS_PORT: 6379
    steps:
      - name: Get Code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: go mod download
